//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Properties = new HashSet<Property>();
            this.Users = new HashSet<User>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
