//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public double SquareFeet { get; set; }
        public string Country { get; set; }
    
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
